import { useEffect, useState } from 'react';
import type { Account, Opportunity, Page, salesApi } from './api';
type Contact = { id: number; name: string; phone: string | null; email: string | null; active: boolean; decisionMaker: boolean };
type Purchase = { id: number; productName: string; orderNumber: string; orderDate: string; quantity: number };
export default function AccountPanel({ account, request, management, canMerge, revision, changed }: { account: Account; request: ReturnType<typeof salesApi>; management: boolean; canMerge: boolean; revision: number; changed: () => void }) {
  const [page,setPage]=useState(0);const [totalPages,setTotalPages]=useState(0);const [opportunities,setOpportunities]=useState<Opportunity[]>([]); const [expanded, setExpanded] = useState(false); const [contacts, setContacts] = useState<Contact[]>([]); const [purchases, setPurchases] = useState<Purchase[]>([]); const [error, setError] = useState('');
  useEffect(() => { if (!expanded) return; let live = true; void Promise.all([request<Page<Contact>>(`/accounts/${account.id}/contacts?page=${page}`), request<Page<Purchase>>(`/accounts/${account.id}/purchases?page=${page}`),request<Page<Opportunity>>(`/opportunities?accountId=${account.id}&page=${page}`)]).then(([c, p, o]) => { if (live) { setContacts(c.content); setPurchases(p.content);setOpportunities(o.content);setTotalPages(Math.max(c.totalPages,p.totalPages,o.totalPages)); } }).catch(e => setError(e.message)); return () => { live = false; }; }, [account.id, request, expanded, revision,page]);
  async function action(path: string, body: unknown, method = 'POST') { try { await request(`/accounts/${account.id}${path}`, method, body); changed(); } catch (e) { setError((e as Error).message); } }
  return <section><button onClick={() => setExpanded(e => !e)}>{expanded ? 'Hide' : 'Show'} contacts and purchasing history</button>{error && <p role="alert">{error}</p>}{expanded && <><h4>Contacts</h4>{contacts.length === 0 && <p>No contacts yet.</p>}{contacts.map(c => <article key={c.id}><b>{c.name}{c.decisionMaker ? ' · Decision maker' : ''}</b><p>{c.phone} {c.email} · {c.active ? 'Active' : 'Previous employer relationship retained'}</p>{management && c.active && <form onSubmit={e => { e.preventDefault(); const d = Object.fromEntries(new FormData(e.currentTarget)); void action(`/contacts/${c.id}/move`, { accountId: Number(d.accountId), reason: d.reason }); }}><label>New employer account ID<input type="number" name="accountId" required /></label><label>Reason<input name="reason" required /></label><button>Record employer change</button></form>}</article>)}<h4>Sales efforts for this account</h4>{opportunities.map(o=><article key={o.id}>Opportunity #{o.id} · {o.origin} · {o.stage} · {o.state} · {o.ownerEmail || "Unassigned"}</article>)}<div className="crm-pager"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous records</button><span>Account records page {page+1}</span><button disabled={page+1>=totalPages} onClick={()=>setPage(p=>p+1)}>Next records</button></div><h4>Zoho purchasing history</h4>{purchases.length === 0 && <p>No known purchases for this account.</p>}{purchases.map(p => <article key={p.id}>{p.productName} · {p.quantity}<small>{p.orderNumber || 'Order'} · {p.orderDate}</small></article>)}{management && !account.zohoCustomerId && <form className="crm-form" onSubmit={e => { e.preventDefault(); const d = Object.fromEntries(new FormData(e.currentTarget)); void action('/customer-link', d, 'PUT'); }}><h4>Confirm Zoho customer identity</h4><label>Zoho customer ID<input name="zohoCustomerId" required /></label><label>Verification reason<input name="reason" required /></label><button>Link confirmed identity</button></form>}{canMerge && <form className="crm-form" onSubmit={e => { e.preventDefault(); const d = Object.fromEntries(new FormData(e.currentTarget)); void action('/merge', { targetAccountId: Number(d.targetAccountId), reason: d.reason }); }}><h4>Merge verified duplicate</h4><p>Move opportunities and contacts to the surviving account; retain this account as an archived reference.</p><label>Surviving account ID<input type="number" name="targetAccountId" required /></label><label>Identity verification reason<input name="reason" required /></label><button>Merge accounts</button></form>}</>}</section>;
}
