import { useState } from 'react';
import type { salesApi, Page } from './api';
type Link = { id: number; zohoOrderId: string; status: string; matchMethod: string };
export default function OrderMatches({ opportunityId, productId, request, canConfirm, changed }: { opportunityId: number; productId: number; request: ReturnType<typeof salesApi>; canConfirm: boolean; changed: () => void }) {
  const [links, setLinks] = useState<Link[]>([]); const [checked, setChecked] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [candidates,setCandidates]=useState<{zohoLineItemId:string;orderNumber:string;orderDate:string}[]>([]);const [page,setPage]=useState(0);const [pages,setPages]=useState(0);
  async function loadCandidates(p:number){try{const result=await request<Page<typeof candidates[number]>>(`/opportunities/${opportunityId}/products/${productId}/order-candidates?page=${p}`);setCandidates(result.content);setPage(p);setPages(result.totalPages);}catch(e){setError((e as Error).message);}}
  return <div>{canConfirm&&<details><summary>Review alternative exact customer/product orders</summary><button onClick={()=>void loadCandidates(0)}>Load candidates</button>{candidates.map(c=><form key={c.zohoLineItemId} onSubmit={e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get("reason");void request<Link>(`/opportunities/${opportunityId}/products/${productId}/order-proposal`,"POST",{lineId:c.zohoLineItemId,reason}).then(l=>{setLinks(rows=>[...rows.filter(x=>x.id!==l.id),l]);changed();}).catch(e=>setError(e.message));}}><p>{c.orderNumber} · {c.orderDate}</p><label>Attribution review reason<input name="reason" required /></label><button>Propose for review</button></form>)}<button disabled={page===0} onClick={()=>void loadCandidates(page-1)}>Previous orders</button><button disabled={page+1>=pages} onClick={()=>void loadCandidates(page+1)}>Next orders</button></details>}<button disabled={busy} onClick={() => { setBusy(true); void request<Link[]>(`/opportunities/${opportunityId}/products/${productId}/order-matches`, 'POST', {}).then(l => { setLinks(l); setChecked(true); changed(); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }}>Check Zoho order matches</button>{error && <p role="alert">{error}</p>}{checked && !links.length && <p>No subsequent matching order. Confirm customer and catalog product identities first.</p>}{links.map(l => <article key={l.id}><p>Order {l.zohoOrderId} · {l.status} · {l.matchMethod}</p>{canConfirm && l.status === 'REVIEW_REQUIRED' && <form onSubmit={e => { e.preventDefault(); const reason = new FormData(e.currentTarget).get('reason'); setBusy(true); void request(`/opportunities/${opportunityId}/order-matches/${l.id}/confirm`, 'POST', { reason }).then(() => { setLinks(rows => rows.map(row => row.id === l.id ? { ...row, status: 'CONFIRMED' } : row)); changed(); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }}><label>Verified identity and timing<input name="reason" required placeholder="Reason for confirming this first order" /></label><button disabled={busy}>Confirm first order</button></form>}</article>)}</div>;
}
