import { useCallback, useEffect, useState } from 'react';
import { Eye, KeyRound, Pencil, Plus, Save, ShieldCheck, Trash2, Users, X } from 'lucide-react';
import './admin-users.css';

type RoleAssignment = {department:string;designation:string};
type ManagedUser = { id:number; email:string; role:string; department?:string; designation?:string; departmentRoles:RoleAssignment[]; globalAccessLevel:string; createdAt:string; permissions:string[]; visibleModules:string[] };
type ModuleRule = {key:string;label:string;departments:string[];configurable:boolean};
const departments = ['SALES','OPERATIONS','FINANCE'];
const designations = ['EXECUTIVE','SENIOR_EXECUTIVE','MANAGER','HEAD'];

export default function AdminUserManagement({api,token,onExpired}: {api:string;token:string;onExpired:()=>void}) {
  const [users,setUsers] = useState<ManagedUser[]>([]); const [busy,setBusy] = useState(true); const [error,setError] = useState(''); const [success,setSuccess] = useState('');
  const [editing,setEditing] = useState<number|null>(null); const [draft,setDraft] = useState({email:'',password:'',role:'USER',globalAccessLevel:'STANDARD',department:'OPERATIONS',designation:'EXECUTIVE',departmentRoles:[{department:'OPERATIONS',designation:'EXECUTIVE'}] as RoleAssignment[]});
  const [newUser,setNewUser] = useState({email:'',password:'',role:'USER',globalAccessLevel:'STANDARD',department:'OPERATIONS',designation:'EXECUTIVE',departmentRoles:[{department:'OPERATIONS',designation:'EXECUTIVE'}] as RoleAssignment[]});
  const [moduleRules,setModuleRules] = useState<ModuleRule[]>([]); const [accessSaving,setAccessSaving] = useState(false);
  const refresh = useCallback(async()=>{setBusy(true);try{const r=await fetch(`${api}/admin/users`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===401){onExpired();return}if(!r.ok)throw new Error(await r.text());setUsers(await r.json())}catch(e){setError(e instanceof Error?e.message:'Could not load users')}finally{setBusy(false)}},[api,token,onExpired]);
  useEffect(()=>{void refresh()},[refresh]);
  useEffect(()=>{fetch(`${api}/admin/department-access`,{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(!r.ok)throw new Error(await r.text());setModuleRules(await r.json())}).catch(e=>setError(e instanceof Error?e.message:'Could not load module access rules'))},[api,token]);
  const saveAccess=async()=>{setAccessSaving(true);setError('');setSuccess('');try{const r=await fetch(`${api}/admin/department-access`,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(moduleRules.map(rule=>({key:rule.key,departments:rule.departments})))});if(!r.ok)throw new Error(await r.text());setModuleRules(await r.json());setSuccess('Department module access updated.')}catch(e){setError(e instanceof Error?e.message:'Could not save module access')}finally{setAccessSaving(false)}};
  const save = async(id:number|null)=>{const body=id===null?newUser:draft;setError('');setSuccess('');try{const r=await fetch(id===null?`${api}/admin/users`:`${api}/admin/users/${id}`,{method:id===null?'POST':'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());setSuccess(id===null?'User created.':'User details updated.');setEditing(null);if(id===null)setNewUser({...newUser,email:'',password:''});else setDraft({...draft,password:''});await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save user')}};
  const remove=async(user:ManagedUser)=>{if(!window.confirm(`Delete ${user.email}? This cannot be undone.`))return;try{const r=await fetch(`${api}/admin/users/${user.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(await r.text());setSuccess('User deleted.');await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not delete user')}};
  const startEdit=(u:ManagedUser)=>{const roles=u.departmentRoles?.length?u.departmentRoles:u.department?[{department:u.department,designation:u.designation||'EXECUTIVE'}]:[];setEditing(u.id);setDraft({email:u.email,password:'',role:u.role||'USER',globalAccessLevel:u.globalAccessLevel||'STANDARD',department:u.department||'',designation:u.designation||'',departmentRoles:roles})};
  const roleEditor=(value:typeof draft,setter:(f:typeof draft)=>void)=><fieldset className="au-role-editor"><legend>Department roles</legend><p>Assign a separate designation in each department. Access combines across assigned roles.</p>{departments.map(department=>{const role=value.departmentRoles.find(r=>r.department===department);return <div className="au-role-row" key={department}><label className="au-role-toggle"><input type="checkbox" checked={!!role} onChange={e=>{const roles=e.target.checked?[...value.departmentRoles,{department,designation:'EXECUTIVE'}]:value.departmentRoles.filter(r=>r.department!==department);setter({...value,departmentRoles:roles,department:roles[0]?.department||'',designation:roles[0]?.designation||''})}}/><b>{department}</b></label>{role&&<select aria-label={`${department} designation`} value={role.designation} onChange={e=>{const roles=value.departmentRoles.map(r=>r.department===department?{...r,designation:e.target.value}:r);setter({...value,departmentRoles:roles,department:roles[0]?.department||'',designation:roles[0]?.designation||''})}}>{designations.map(d=><option key={d} value={d}>{d.replace('_',' ')}</option>)}</select>}</div>})}</fieldset>;
  const fields=(value:typeof draft,setter:(f:typeof draft)=>void,includeCredentials:boolean,isEdit=false)=> <>
    <label>Email<input type="email" required value={value.email} onChange={e=>setter({...value,email:e.target.value})}/></label>
    {includeCredentials&&<label>{isEdit?'New password (optional)':'Initial password'}<input type="password" required={!isEdit} minLength={8} autoComplete="new-password" value={value.password} onChange={e=>setter({...value,password:e.target.value})} placeholder={isEdit?'Leave blank to keep current password':'At least 8 characters'} /></label>}
    <label>Global access<select value={value.globalAccessLevel} onChange={e=>setter({...value,globalAccessLevel:e.target.value,role:e.target.value==='ADMIN'?'ADMIN':'USER'})}><option value="STANDARD">Standard</option><option value="ADMIN">Admin</option></select></label>
    {roleEditor(value,setter)}
  </>;
  return <main className="admin-users-page"><header className="au-heading"><div><span>OWNER ACCESS</span><h1>User management</h1><p>Manage credentials and inspect each account’s module access.</p></div><b><ShieldCheck size={16}/> Single Super Admin</b></header>
    {error&&<div className="au-message error">{error}</div>}{success&&<div className="au-message success">{success}</div>}
    <details className="au-create"><summary className="au-section-title"><Plus size={18}/><div><h2>Create account</h2><p>Super Admin access remains reserved for the owner account.</p></div></summary><div className="au-form">{fields(newUser,setNewUser,true)}<button className="au-primary" onClick={()=>void save(null)} disabled={!newUser.email||newUser.password.length<8}><Plus size={16}/> Create user</button></div></details>
    <details className="au-access-settings"><summary className="au-section-title"><Eye size={18}/><div><h2>Department module access</h2><p>Set the departments allowed to open each module. Seniority and server-side data rules still apply.</p></div></summary><div className="au-access-table">{moduleRules.map(rule=><div className="au-access-rule" key={rule.key}><strong>{rule.label}</strong><div>{departments.map(department=><label key={department}><input type="checkbox" checked={rule.departments.includes(department)} onChange={e=>setModuleRules(current=>current.map(item=>item.key===rule.key?{...item,departments:e.target.checked?[...item.departments,department]:item.departments.filter(d=>d!==department)}:item))}/>{department}</label>)}</div></div>)}</div><button className="au-primary" onClick={()=>void saveAccess()} disabled={accessSaving}>{accessSaving?'Saving…':'Save module access'}</button></details>
    <section className="au-users"><div className="au-section-title"><Users size={18}/><div><h2>Registered users <small>{users.length}</small></h2><p>Module access is calculated from each user’s department, designation, and access level.</p></div></div>
      {busy?<p className="au-empty">Loading accounts…</p>:<div className="au-list">{users.map(u=><article className="au-user" key={u.id}>
        <div className="au-user-head"><div className="au-avatar">{u.email.slice(0,1).toUpperCase()}</div><div className="au-ident"><strong>{u.email}</strong><span>{u.globalAccessLevel} · {(u.departmentRoles?.length?u.departmentRoles.map(r=>`${r.department} ${r.designation.replace('_',' ')}`).join(' · '):'No department')}</span></div><span className={`au-level ${u.globalAccessLevel.toLowerCase()}`}>{u.globalAccessLevel==='SUPER_ADMIN'?'OWNER':u.globalAccessLevel}</span>{u.globalAccessLevel!=='SUPER_ADMIN'&&editing!==u.id&&<div className="au-actions"><button title="Edit user" onClick={()=>startEdit(u)}><Pencil size={16}/><span>Edit</span></button><button className="delete" title="Delete user" onClick={()=>void remove(u)}><Trash2 size={16}/><span>Delete</span></button></div>}</div>
        {editing===u.id&&<div className="au-editor"><div className="au-form">{fields(draft,setDraft,true,true)}</div><div className="au-editor-actions"><button className="au-primary" onClick={()=>void save(u.id)} disabled={!!draft.password&&draft.password.length<8}><Save size={15}/> Save changes</button><button className="au-secondary" onClick={()=>setEditing(null)}><X size={15}/> Cancel</button></div><p className="au-password-help"><KeyRound size={14}/> Setting a new password signs the user out of existing sessions.</p></div>}
        <details className="au-access"><summary><Eye size={15}/> View module access <span>{u.visibleModules.length} modules</span></summary><div className="au-module-list">{u.visibleModules.map(m=><span key={m}>{m}</span>)}</div><h3>Permissions</h3><div className="au-module-list">{u.permissions.length?u.permissions.map(p=><span key={p}>{p}</span>):<em>No additional finance permissions</em>}</div></details>
      </article>)}</div>}</section>
  </main>;
}
