import {Metric} from './sales/SalesInsights';
const groups=[{title:'Pipeline & commercial outcomes',items:{prospectsAdded:'Acquisition prospects added',expansionsAdded:'Expansion opportunities added',activeMonthlyPipelineINR:'Current monthly pipeline',weightedMonthlyPipelineINR:'Weighted monthly pipeline (estimate)',winRate:'Opportunity win rate',partialWins:'Partial wins',productLineConversion:'Product-line conversion',wonMonthlyValueINR:'Monthly value won',salesVelocityINRMonthlyValuePerDay:'Sales velocity (monthly value/day)',pipelineUnknownOrZeroValueCount:'Unconfirmed pipeline values'}},
 {title:'Execution & efficiency',items:{approaches:'Outbound contact attempts',firstApproach:'Time to first approach',assignmentToFirstApproach:'Assignment to first approach',followupCompliance:'Follow-ups completed on time',cancelledTasks:'Cancelled follow-ups',demosBooked:'Demos booked',demosCompleted:'Demos completed',demoBooking:'Demo booking rate',demoCompletion:'Demo completion rate',demoNoShow:'Demo no-show rate',stageConversion:'New to interested conversion',salesCycle:'Sales cycle to first win'}},
 {title:'Won-to-order realization',items:{wonToFirstOrder:'Won products with a first order',orderMatchReviewRequired:'Order matches awaiting review',disqualified:'Disqualified opportunities',averageWonDealMonthlyValueINR:'Average monthly value per won deal'}}];
export default function CeoCrmMetrics({data,error}:{data:Record<string,unknown>|null;error:string}){
 if(error)return <p role="alert">CRM metrics could not be loaded: {error}</p>;
 if(!data)return <p role="status">Loading CRM metrics…</p>;
 return <><p>Event period: {String(data.from)} to {String(data.to)}. Pipeline is current; value estimates include all covered outlets.</p>{groups.map(g=><section className="ceo-crm-subgroup" key={g.title}><h3>{g.title}</h3><div className="ceo-metrics">{Object.entries(g.items).map(([key,title])=><article className="ceo-metric" key={key}><span>{title}</span><Metric name={key} value={data[key]}/></article>)}</div></section>)}<section className="ceo-crm-subgroup"><h3>Inbound & outbound lead mix</h3><p>Created opportunities by month. Shares include unknown direction in the denominator.</p><div className="ceo-metrics">{Object.entries((data.leadDirectionByMonth||{}) as Record<string,{inbound:unknown;outbound:unknown;unknown:number}>).map(([month,m])=><article className="ceo-metric" key={month}><h4>{month}</h4><span>Inbound</span><Metric name="inbound" value={m.inbound}/><span>Outbound</span><Metric name="outbound" value={m.outbound}/><small>Unknown direction: {m.unknown}</small></article>)}</div></section><details className="ceo-crm-definitions"><summary>CRM reporting definitions</summary><p>{String(data.convention||'')}</p><p>{String(data.leadDirectionConvention||'')}</p></details></>;
}
