import ResponsiveTable from './ResponsiveTable';
import { useEffect, useState } from 'react';

type PromiseRow = { logId: number; customerId: string; customerName: string; invoiceReference: string; owner: string; salesperson?: string; promiseDate: string; promiseAmount: number; receivedByPromise: number; shortfall: number; broken: boolean; verified: boolean };
type Data = { rows: PromiseRow[]; accountingAvailable: boolean; asOf: string; paymentSync: { lastSuccess?: string; error?: string } };
type Props = { api: string; token: string; revision: number; onExpired: () => void; onFindInvoices?: () => void; onFollowup: (invoice: { customerId: string; customerName: string; invoiceReference: string }) => void };
const money = (n: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(n);
const date = (s?: string) => s ? new Date(`${s.slice(0, 10)}T12:00:00`).toLocaleDateString('en-IN') : 'Not synced';
export default function FinancePaymentPromises({ api, token, revision, onExpired, onFollowup, onFindInvoices }: Props) {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState('ALL'); const [refresh, setRefresh] = useState(0);
  useEffect(() => { const abort = new AbortController(); const load = async () => { try { const r = await fetch(`${api}/accounts/payment-promises`, { headers: { Authorization: `Bearer ${token}` }, signal: abort.signal }); if (r.status === 401) { onExpired(); return; } if (!r.ok) throw new Error('Unable to load payment promises.'); setData(await r.json()); setError(''); } catch (e) { if (!abort.signal.aborted) setError(e instanceof Error ? e.message : 'Unable to load payment promises.'); } }; void load(); const timer = window.setInterval(load, 60000); return () => { abort.abort(); window.clearInterval(timer); }; }, [api, token, revision, refresh, onExpired]);
  const state = (p: PromiseRow) => !data?.accountingAvailable ? 'Awaiting receipts' : p.shortfall <= 0 ? 'Fulfilled' : p.broken ? 'Missed' : !p.verified && p.promiseDate < data.asOf.slice(0, 10) ? 'Awaiting fresh sync' : 'Pending';
  const rows = (data?.rows ?? []).filter(p => `${p.customerName} ${p.invoiceReference} ${p.owner} ${p.salesperson ?? ''}`.toLowerCase().includes(query.toLowerCase()) && (status === 'ALL' || status === 'OPEN' && state(p) !== 'Fulfilled' || status === state(p))).sort((a, b) => a.promiseDate.localeCompare(b.promiseDate));
  return <section className="fp-promises"><div className="fp-promises-header"><div><h3>Payment promises</h3><p>Latest promise per invoice. Log the next conversation here when a customer delays or renews their commitment.</p></div><div className="fp-workspace-actions">{onFindInvoices && <button className="fp-log-promise" onClick={onFindInvoices}>Log a payment promise</button>}<button onClick={() => setRefresh(v => v + 1)}>Refresh promises</button></div></div><div className="fp-promise-filters"><input aria-label="Search payment promises" placeholder="Search customer, invoice, owner or salesperson…" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="Payment promise status" value={status} onChange={e => setStatus(e.target.value)}>{['ALL', 'OPEN', 'Pending', 'Missed', 'Fulfilled', 'Awaiting receipts', 'Awaiting fresh sync'].map(s => <option key={s}>{s}</option>)}</select></div>{error && <p role="alert" className="followup-error">{error}</p>}{data && <p className="followup-hint">Receipt sync: {date(data.paymentSync.lastSuccess)}. Receipt totals use allocations to this invoice from contact date through deadline. Recording a promise does not mark an invoice paid.</p>}{data?.paymentSync.error && <p role="alert" className="followup-error">{data.paymentSync.error}</p>}<div className="table-responsive"><ResponsiveTable><thead><tr><th>Customer / invoice</th><th>Owner</th><th>Salesperson</th><th>Deadline</th><th>Promised</th><th>Received by deadline</th><th>Shortfall</th><th>Status</th><th>Next action</th></tr></thead><tbody>{rows.map(p => <tr key={`${p.customerId}-${p.invoiceReference}`}><td data-label="Customer / invoice"><strong>{p.customerName}</strong><small>{p.invoiceReference}</small></td><td data-label="Owner">{p.owner}</td><td data-label="Salesperson">{p.salesperson || 'Unassigned'}</td><td data-label="Deadline">{date(p.promiseDate)}</td><td data-label="Promised">{money(p.promiseAmount)}</td><td data-label="Received by deadline">{data?.accountingAvailable ? money(p.receivedByPromise) : 'N/A'}</td><td data-label="Shortfall">{data?.accountingAvailable ? money(p.shortfall) : 'N/A'}</td><td data-label="Status">{state(p)}</td><td data-label="Next action"><button onClick={() => onFollowup(p)}>Log next follow-up</button></td></tr>)}</tbody></ResponsiveTable></div>{data && !rows.length && <p>{data.rows.length ? 'No promises match these filters.' : 'No payment promises recorded yet. Tick Customer promised payment when logging a finance follow-up and enter the amount and deadline.'}</p>}{!data && !error && <p role="status">Loading payment promises…</p>}</section>;
}
