import { useEffect,useMemo,useState } from 'react';
import { Activity,AlertCircle,CalendarClock,CheckCircle2,Clock3,MessageSquare,Phone,RefreshCw,Search,Users,X } from 'lucide-react';
import './sales-followup.css';

type AlertRow={customerId:string;customerName:string;productId:string;productName:string;predictedOrderDate:string;daysUntilPredicted:number|null;lastOrderDate:string|null;followupDueDate:string;daysLate:number;priority:string;lastFollowupSummary?:string;lastFollowup?:any};
type TeamData={staff:any[];lateEvents:any[];asOf:string};
const channels=['CALL','WHATSAPP','EMAIL','IN_PERSON'];
const dateLabel=(value?:string)=>value?new Date(`${value}T00:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—';

export default function SalesFollowupDashboard({api,token,isSuperAdmin,onExpired}:{api:string;token:string;isSuperAdmin:boolean;onExpired:()=>void}){
 const [rows,setRows]=useState<AlertRow[]>([]);const [history,setHistory]=useState<any[]>([]);const [team,setTeam]=useState<TeamData>({staff:[],lateEvents:[],asOf:''});const [view,setView]=useState<'calls'|'history'|'team'>('calls');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [target,setTarget]=useState<AlertRow|null>(null);const [saving,setSaving]=useState(false);const [channel,setChannel]=useState('CALL');const [response,setResponse]=useState('');const [mode,setMode]=useState<'AUTO'|'MANUAL'|'NONE'>('AUTO');const [nextDate,setNextDate]=useState('');const [status,setStatus]=useState('FOLLOWED_UP');const [search,setSearch]=useState('');const [priority,setPriority]=useState('ALL');
 const headers={Authorization:`Bearer ${token}`};
 const refresh=async()=>{setLoading(true);setError('');try{const [a,h]=await Promise.all([fetch(`${api}/sales-followups/alerts`,{headers}),fetch(`${api}/sales-followups/history`,{headers})]);if(a.status===401||h.status===401){onExpired();return}if(!a.ok||!h.ok)throw new Error('Could not load recurring sales follow-ups.');setRows(await a.json());setHistory(await h.json());if(isSuperAdmin){const t=await fetch(`${api}/sales-followups/team-activity`,{headers});if(t.ok)setTeam(await t.json())}}catch(e){setError(e instanceof Error?e.message:'Could not load recurring sales follow-ups.')}finally{setLoading(false)}};
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),60000);return()=>window.clearInterval(timer)},[api,token,isSuperAdmin]);
 const stats=useMemo(()=>({due:rows.filter(r=>r.priority==='DUE_TODAY'||r.priority==='OVERDUE').length,overdue:rows.filter(r=>r.priority==='OVERDUE').length,handled:history.length}),[rows,history]);
 const filteredRows=useMemo(()=>rows.filter(row=>(priority==='ALL'||row.priority===priority)&&`${row.customerName} ${row.productName}`.toLowerCase().includes(search.toLowerCase())),[rows,priority,search]);
 const openLog=(row:AlertRow)=>{setTarget(row);setChannel('CALL');setResponse('');setMode('AUTO');setNextDate('');setStatus('FOLLOWED_UP')};
 const submit=async()=>{if(!target||!response.trim()||(mode==='MANUAL'&&!nextDate))return;setSaving(true);setError('');try{const r=await fetch(`${api}/sales-followups`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({customer_id:target.customerId,product_id:target.productId,channel,response, next_followup_mode:mode,next_followup_date:mode==='MANUAL'?nextDate:null,status})});if(r.status===401){onExpired();return}if(!r.ok)throw new Error(await r.text());setTarget(null);await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not save follow-up.')}finally{setSaving(false)}};
 const deleteEntry=async(entry:any)=>{if(!window.confirm('Delete this follow-up log?'))return;setSaving(true);try{const r=await fetch(`${api}/sales-followups/${entry.log.id}`,{method:'DELETE',headers});if(!r.ok)throw new Error(await r.text());await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not delete follow-up.')}finally{setSaving(false)}};
 const submitEdit=async(entry:any,form:any)=>{setSaving(true);try{const r=await fetch(`${api}/sales-followups/${entry.log.id}`,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({customer_id:entry.log.customerId,product_id:entry.log.productId,channel:form.channel,response:form.response,next_followup_mode:form.mode,next_followup_date:form.mode==='MANUAL'?form.date:null,status:form.status})});if(!r.ok)throw new Error(await r.text());await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not update follow-up.')}finally{setSaving(false)}};
 return <main className="sf-page"><header className="sf-header"><div><span>RECURRING SALES</span><h1>Recurring Sales Follow-up</h1><p>Follow up with existing customers for recurring orders around predicted reorder dates, and record the next action.</p></div><button className="sf-sync" onClick={()=>void refresh()} aria-label="Refresh recurring sales follow-ups"><RefreshCw size={17}/></button></header>
 {error&&<div className="sf-error"><AlertCircle size={17}/>{error}</div>}
 <section className="sf-stats"><article><span><CalendarClock/></span><small>Due today or overdue</small><strong>{stats.due}</strong></article><article className={stats.overdue?'sf-stat-warn':''}><span><Clock3/></span><small>Overdue follow-ups</small><strong>{stats.overdue}</strong></article><article><span><CheckCircle2/></span><small>Logged follow-ups</small><strong>{stats.handled}</strong></article></section>
 <nav className="sf-tabs"><button className={view==='calls'?'active':''} onClick={()=>setView('calls')}>Recurring follow-ups</button><button className={view==='history'?'active':''} onClick={()=>setView('history')}>Recurring sales history</button>{isSuperAdmin&&<button className={view==='team'?'active':''} onClick={()=>setView('team')}>Private team scorecard</button>}</nav>
 {loading?<p className="sf-empty">Loading recurring sales follow-ups…</p>:view==='calls'?<><div className="sf-filters"><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer or product"/></label><select aria-label="Filter follow-up priority" value={priority} onChange={e=>setPriority(e.target.value)}><option value="ALL">All priorities</option><option value="OVERDUE">Overdue</option><option value="DUE_TODAY">Due today</option><option value="UPCOMING">Upcoming</option><option value="PLANNED">Planned</option></select><span>{filteredRows.length} follow-ups</span></div><section className="sf-list">{filteredRows.length?filteredRows.map(row=><article className={`sf-card sf-${row.priority.toLowerCase()}`} key={`${row.customerId}-${row.productId}`}><div className="sf-card-head"><div className="sf-avatar">{(row.customerName||'?').slice(0,1)}</div><div className="sf-title"><strong>{row.customerName}</strong><span>{row.productName}</span></div><b className="sf-priority">{row.priority==='OVERDUE'?`${row.daysLate}d overdue`:row.priority.replace('_',' ')}</b></div><div className="sf-details"><span><small>Predicted reorder</small><b>{dateLabel(row.predictedOrderDate)}</b></span><span><small>Last order</small><b>{dateLabel(row.lastOrderDate||undefined)}</b></span><span><small>Follow-up due</small><b>{dateLabel(row.followupDueDate)}</b></span></div>{row.lastFollowupSummary&&<p className="sf-response"><MessageSquare size={14}/>{row.lastFollowupSummary}</p>}<div className="sf-card-foot"><span>{row.lastFollowup?`Last contacted by ${row.lastFollowup.followupBy}`:'No follow-up logged yet'}</span><button onClick={()=>openLog(row)}><Phone size={15}/>{row.lastFollowup?'Log another follow-up':'Log follow-up'}</button></div></article>):<div className="sf-empty">No matching recurring sales follow-ups.</div>}</section></>:view==='history'?<section className="sf-history">{history.length?history.map(entry=><SalesHistory key={entry.log.id} entry={entry} onEdit={submitEdit} onDelete={deleteEntry} saving={saving}/>):<div className="sf-empty">No recurring sales follow-ups logged yet.</div>}</section>:<SalesTeam data={team}/>}
 {target&&<div className="sf-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setTarget(null)}}><section className="sf-modal" role="dialog" aria-modal="true"><header><div><small>LOG RECURRING SALES CONTACT</small><h2>{target.customerName}</h2><p>{target.productName}</p></div><button aria-label="Close" onClick={()=>setTarget(null)}><X size={18}/></button></header><label>Channel<select value={channel} onChange={e=>setChannel(e.target.value)}>{channels.map(c=><option key={c}>{c}</option>)}</select></label><label>Customer response<textarea value={response} onChange={e=>setResponse(e.target.value)} placeholder="What did the customer say?" rows={4}/></label><fieldset><legend>Follow-up due date</legend><label className="sf-radio"><input type="radio" checked={mode==='AUTO'} onChange={()=>setMode('AUTO')}/>Automatic · 3 days</label><label className="sf-radio"><input type="radio" checked={mode==='MANUAL'} onChange={()=>setMode('MANUAL')}/>Set a date</label><label className="sf-radio"><input type="radio" checked={mode==='NONE'} onChange={()=>setMode('NONE')}/>No further follow-up needed</label>{mode==='MANUAL'&&<input type="date" value={nextDate} onChange={e=>setNextDate(e.target.value)}/>}</fieldset><label>Outcome<select value={status} onChange={e=>setStatus(e.target.value)}><option value="FOLLOWED_UP">Contact completed</option><option value="PENDING">Contact not completed</option><option value="ORDER_PLACED">Order placed</option><option value="NOT_INTERESTED">Not interested</option></select></label><footer><button className="sf-cancel" onClick={()=>setTarget(null)}>Cancel</button><button className="sf-save" onClick={()=>void submit()} disabled={saving||!response.trim()||(mode==='MANUAL'&&!nextDate)}>{saving?'Saving…':'Save follow-up'}</button></footer></section></div>}
 </main>
}

function SalesHistory({entry,onEdit,onDelete,saving}:{entry:any;onEdit:(entry:any,form:any)=>void;onDelete:(entry:any)=>void;saving:boolean}){const [editing,setEditing]=useState(false);const [form,setForm]=useState({channel:entry.log.channel,response:entry.log.response,mode:entry.log.nextFollowupMode||'AUTO',date:entry.log.nextFollowupDate||'',status:entry.log.status});return <article className="sf-history-card"><div><strong>{entry.log.customerName}</strong><span>{entry.log.productName} · {entry.log.followupBy}</span></div><p>{entry.log.response}</p><small>{entry.log.channel} · {dateLabel(entry.log.followupDate?.slice(0,10))} · Follow-up: {dateLabel(entry.log.nextFollowupDate)}</small>{entry.editable&&<span className="sf-history-actions"><button onClick={()=>setEditing(!editing)}>{editing?'Close':'Edit'}</button><button onClick={()=>onDelete(entry)}>Delete</button></span>}{editing&&<div className="sf-edit"><select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}>{channels.map(c=><option key={c}>{c}</option>)}</select><textarea value={form.response} onChange={e=>setForm({...form,response:e.target.value})}/><select value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option value="AUTO">Automatic · 3 days</option><option value="MANUAL">Manual date</option><option value="NONE">No further follow-up</option></select>{form.mode==='MANUAL'&&<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/>}<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="FOLLOWED_UP">Contact completed</option><option value="PENDING">Contact not completed</option><option value="ORDER_PLACED">Order placed</option><option value="NOT_INTERESTED">Not interested</option></select><button disabled={saving} onClick={()=>void onEdit(entry,form)}>Save edit</button></div>}</article>}

function SalesTeam({data}:{data:TeamData}){const staff=data.staff.reduce((sum,p)=>sum+p.followupsLogged,0);const late=data.staff.reduce((sum,p)=>sum+p.lateFollowups,0);const overdue=data.staff.reduce((sum,p)=>sum+p.overdueCustomers,0);return <><aside className="sf-private-note"><Activity size={17}/> Private Super Admin view · activity metrics are visible only to the founder.</aside><section className="sf-stats"><article><span><Users/></span><small>Sales team members</small><strong>{data.staff.length}</strong></article><article><span><CheckCircle2/></span><small>Contacts logged</small><strong>{staff}</strong></article><article className={late+overdue?'sf-stat-warn':''}><span><Clock3/></span><small>Late + overdue actions</small><strong>{late+overdue}</strong></article></section><section className="sf-team-grid">{data.staff.map(person=><article key={person.followupBy}><header><b>{person.followupBy}</b><strong>{person.performanceScore}<small>/100</small></strong></header><p>{person.customersHandled} customers · {person.followupsLogged} logged</p><div className="sf-scorebar"><i style={{width:`${person.performanceScore}%`}}/></div><small>{person.onTimeRate}% on time · {person.lateFollowups} late · {person.overdueCustomers} open overdue</small></article>)}</section><section className="sf-history"><h2>Late and overdue recurring sales follow-ups</h2>{data.lateEvents.map((event,index)=><article className="sf-history-card" key={`${event.customerId}-${event.productName}-${index}`}><strong>{event.customerName} · {event.productName}</strong><span>{event.followupBy} · {event.lateDays} days late · due {dateLabel(event.scheduledDate)}</span></article>)}</section></>}
